### PR TITLE
🚧 Installer

### PR DESCRIPTION
**Pull request by humboldt123**

### CODE REVIEW

**Comment by humboldt123** [comment]
Do not merge.

**Comment by l1ving** [comment]
Installe

**Comment by JerryWester** [comment]
Installe

**Comment by bytechef** [comment]
🚨 ⚠️ 🚫 🚧 DO NOT MERGE 🚨 ⚠️ 🚫 🚧 DO NOT MERGE 🚨 ⚠️ 🚫 🚧 DO NOT MERGE 🚨 ⚠️ 🚫 🚧 DO NOT MERGE 🚨 ⚠️ 🚫 🚧 DO NOT MERGE 🚨 ⚠️ 🚫 🚧

**Comment by l1ving** [comment]
# :frog:

**Comment by DisNin** [comment]
mamma mia

**Comment by zeroeightysix** [comment]
This is the comments section dedicated to a contribution to KAMI. It is not a place to shitpost.

**Comment by humboldt123** [comment]
Todo:

- Detect if you have the *latest* version of the mod
- Let user choose from MultiMC instances
- Delete `fabic-installer.jar` after installing
- Don't install until you install `fabric-installer.jar`
- Detect fabric better (via versions folder) and prompt to install latest fabric if not
- Add more backgrounds
- Clean code

**Comment by humboldt123** [comment]
Todo:

- [x] Detect if you have the *latest* version of the mod
- [ ] Let user choose from MultiMC instances
- [x] Delete `fabic-installer.jar` after installing
- [x] Don't install until you install `fabric-installer.jar`
- [x] Detect fabric better (via versions folder) and prompt to install latest fabric if not
- [x] Add more backgrounds
- [x] Clean code
- [x] find and delete older kami versions
- [ ] get instances folder for osx

**Comment by humboldt123** [comment]
Anything relating to MultiMC will be in a separate PR

**Review by zeroeightysix — DISMISSED** [review]
Please fix actions build.

Also, all new code for KAMI should be written in kotlin - please fix.

**Comment by humboldt123** [comment]
The thing builds on my computer normally and I didn't change anything major for the actions build to fail.

**Comment by humboldt123** [comment]
The error was in a gradle file which I didn't' even change between the two commits

**Review by zeroeightysix — CHANGES_REQUESTED** [review]
* There is no indication of progress anywhere at all, making the installation process quite confusing - you don't know if the installer is doing anything at all until some random popup happens.

* I don't like how it looks pretty much the same as kami blue's installer.

* You can not choose the version you wish to install

* While this can come in a later PR, I'd prefer if the installer also gives you the option to install multiconnect or sodium alongside KAMI.

**Comment by humboldt123** [comment]
I don't have time to do this is right now, I will get back to this later so don't close.

**Comment by humboldt123** [comment]
I might use swing when I do.

**Pull request closed without merging**
