### PR TITLE
added AutoTrap

### PR DESCRIPTION
**Pull request by blockparole**
Im not quite sure how to represent a dependencie of a pr on another pr, but this pr also implements the BlockInteractionHelper Util Class. Its the same file as in the AutoFeetPlace [pr](https://github.com/zeroeightysix/KAMI/pull/141), so it should automerge 🙈 .

### CODE REVIEW

**Comment by blockparole** [comment]
> After some research, it seems that ticks per block seems to be the way to go here. It causes desync for some people, other then was i was experiencing while testing.

I gonna change the mechanics for this, pls dont merge yet.

**Comment by blockparole** [comment]
This has the same problem on 2b2t as stated [here](https://github.com/zeroeightysix/KAMI/pull/141#issuecomment-558273626).

**Comment by blockparole** [comment]
> 
> 
> This has the same problem on 2b2t as stated [here](https://github.com/zeroeightysix/KAMI/pull/141#issuecomment-558273626).

this is a lot nicer now, problem should be resolved

**Comment by S-B99** [comment]
What actually was changed to solve this? Just more efficient or a proper tick delay? Just curious

**Comment by blockparole** [comment]
a lot of stuff actually, i changed like half the modules code.
basically its more delay options for the user to choose from.

**Comment by zeroeightysix** [comment]
Also closing (see https://github.com/zeroeightysix/KAMI/pull/142).

Sorry! I hope to reimplement these modules in fabric, but doing it from the same commits as these PRs is near impossible.

**Pull request closed without merging**
