### PR TITLE
added seppukus FastBow

### PR DESCRIPTION
**Pull request by blockparole**
Kami Blue also [has it](https://github.com/S-B99/KAMI/blob/features-master/src/main/java/me/zeroeightsix/kami/module/modules/sdashb/combat/BowSpam.java), so i figured i could add it here too.

### CODE REVIEW

**Comment by S-B99** [comment]
Bruh I was gonna pr but I'm in school

**Comment by blockparole** [comment]
was faster lol

**Comment by zeroeightysix** [comment]
Not sure how the licensing works on this. Are we allowed to re-use this code?

**Comment by S-B99** [comment]
Yes, as seppuku is GPL3

**Comment by zeroeightysix** [comment]
Thanks!

**Comment by 0-x-2-2** [comment]
> Not sure how the licensing works on this. Are we allowed to re-use this code?

No. If Seppuku is GPL and KAMI is LGPL unless Seppuku has some sort of LGPL exemption (I doubt it) this is not allowed.

**Comment by blockparole** [comment]
Oh i didnt realize this. If this is the case this should be reverted ofc.

**Comment by S-B99** [comment]
Can you not sublicense gpl?

**Comment by 0-x-2-2** [comment]
> Can you not sublicense gpl?

GPL projects are allowed to use LGPL code but not the other way around.

LGPL is allowed to be used by proprietary code as a library, unlike GPL  licensed code. So technically someone could use KAMI code as a library in a proprietary mod.

**Comment by S-B99** [comment]
Thanks, makes sense

**Pull request merged**
