### PR TITLE
Feature/close new chunk saving

### PR DESCRIPTION
**Pull request by IronException**

### CODE REVIEW

**Comment by dominikaaaa** [comment]
@zeroeightysix this should be implemented from https://github.com/zeroeightysix/KAMI/commit/dd91b2d1098369b97f5aa7961895c54c83643501 and then closed

**Comment by zeroeightysix** [comment]
@IronException It's near impossible to use your original commit for the fabric implementation. Would you like to redo this on the fabric branch, or do you not mind if I port the code?

**Comment by dominikaaaa** [comment]
I mean it just adds a close file on disable

**Comment by zeroeightysix** [comment]
It's still IronException's work. I think it's fair to give him a chance to get this done in a commit with his name plastered onto it.

**Comment by zeroeightysix** [comment]
Closing due to inactivity

**Comment by IronException** [comment]
oh damn how do I just see this now. Sorry my bad

**Pull request closed without merging**
