### PR TITLE
Improved and Kotlinized Blink

### PR DESCRIPTION
**Pull request by humboldt123**

### CODE REVIEW

**Comment by humboldt123** [comment]
No clue why the say command is in this pr but my git has been acting up

**Comment by JerryWester** [comment]
You might want to start making forks when adding a new feature (i.e.: `feature/kotlin-blink`)

**Comment by 5HT2** [comment]
I taught you how to fix your git earlier. In the future, make a new branch based off of 086's repo

**Comment by zeroeightysix** [comment]
Please fix the PR first. You're undoing my work on brightness this way.

**Comment by 5HT2** [comment]
Note, that that only happens if your branch is off the main tree or you edited those files while behind the remote.

**Pull request closed without merging**
