### PR TITLE
Baritone integration

### PR DESCRIPTION
**Pull request by zeroeightysix**
This PR adds baritone integration.
KAMI will **not** include baritone by default. Instead, if the user installs baritone alongside KAMI, the integration will be enabled.

If there are any cool integrations KAMI is missing or other 'must have's related to baritone, please respond to this PR.

### CODE REVIEW

**Comment by dominikaaaa** [comment]
Aura should pause Baritone, along with AutoEat. Safewalk, Step and Jesus (if you have them) should enable the baritone compatibility setting for them.

**Comment by dominikaaaa** [comment]
Also maybe a setting menu in the gui for commonly used baritone settings would be nice

**Comment by dominikaaaa** [comment]
We also show the current Baritone process in the HUD via this
```kotlin
Optional<IBaritoneProcess> process = BaritoneAPI.getProvider().getPrimaryBaritone().getPathingControlManager().mostRecentInControl();
            if (!frameFinal.isMinimized() && process.isPresent()) {
                AutoWalk autoWalk = MODULE_MANAGER.getModuleT(AutoWalk.class);
                if (process.get() != KamiMod.pauseProcess && autoWalk.isEnabled() && autoWalk.mode.getValue().equals(AutoWalk.AutoWalkMode.BARITONE) && AutoWalk.direction != null) {
                    processes.addLine("Process: AutoWalk (" + AutoWalk.direction + ")");
                } else {
                    processes.addLine("Process: " + process.get().displayName());
                }
            }
```
Not sure how different the syntax is for Fabritone

**Comment by zeroeightysix** [comment]
> Not sure how different the syntax is for Fabritone

The API is identical apparently. Looks like most of fabritone has been merged into baritone already.

**Comment by zeroeightysix** [comment]
Stable enough to merge, further modifications to baritone integration will be done on main branch.

**Comment by zeroeightysix** [comment]
@leijurv integration badge when?

**Comment by leijurv** [comment]
> most of fabritone has been merged into baritone already

There have been PRs from the fabritone gamers for sure - it has been a symbiosis in which they are more or less the exact same thing now lol

> integration badge when?

What version(s) of the game is this for?

**Comment by dominikaaaa** [comment]
> What version(s) of the game is this for?

It's currently built on 1.16.2, I'm sure it'll be updated to 1.16.3 once that's stable

**Pull request merged**
