### PR TITLE
please merge

### PR DESCRIPTION
**Pull request by humboldt123**

### CODE REVIEW

**Comment by humboldt123** [comment]
lgtm please merge!!!!!

**Comment by humboldt123** [comment]
image

**Comment by JerryWester** [comment]
What was the point of this?

**Comment by humboldt123** [comment]
stop being mean

**Comment by sourTaste000** [comment]
makes you fly in minecraft... look at the annotation

**Comment by JerryWester** [comment]
It doesn't though, it only increases your velocity a lot when you're in water/lava

**Comment by humboldt123** [comment]
censhorship

**Pull request closed without merging**
