### PR TITLE
Added a cloned player model to blink

### PR DESCRIPTION
**Pull request by Cuhnt**
Took the cloned player code from freecam and put it into blink. My coding isn't great and it probably has a lot of unnecessary and dumb stuff, but most of the code wasn't made by me, so it actually does work. Unlike most things I make 😎.

### CODE REVIEW

**Comment by Cuhnt** [comment]
Note: Building was successful for me multiple times.

**Comment by S-B99** [comment]
Why would you ever build more then once? It's not fucking quantum mechanics, it won't change if the code doesn't change

**Comment by Cuhnt** [comment]
The Travis CL check failed to build, so I tested it on a few different VMs to see if there was some problem (ik that sounds dumb as fuck but idk I have had dumber issues). Sorry, probably should have mentioned that. There wasn't any problems for any of the ones I tried (Windows 10, Ubuntu, Mint), Despite it failing the check

**Comment by zeroeightysix** [comment]
Looks good. I don't know why the CI build is failing.

**Pull request merged**
