### PR TITLE
Sprint fix

### PR DESCRIPTION
**Pull request by blockparole**
Fix for multiple Sprint Modules showing up, proposed by cookie [here](https://github.com/S-B99/KAMI/issues/22#issuecomment-546729234).

### CODE REVIEW

**Comment by blockparole** [comment]
wrong branch

**Comment by blockparole** [comment]
no correct branch, uh i kinda messed up by doing the auto32k on master branch

**Comment by blockparole** [comment]
uh what to do, should i wait with this pr until the last is resolved?

**Comment by S-B99** [comment]
Yes, wait. or undo the sprint fix and add it to a new branch made from 086 and make a separate pr with that

**Comment by blockparole** [comment]
Ye, the sprint fix is on its own branch `blockparole:sprint-fix`, but the other commits are on master, just gonna wait.

**Comment by S-B99** [comment]
Screenshot_20191027_212539
You also did sprint fix here

**Comment by blockparole** [comment]
Ye, this is the `blockparole:sprint-fix` branch, `blockparole:master` is still at [2a8bff1ef705d06fa7bfa9b80a482a87848cfb8d](https://github.com/zeroeightysix/KAMI/pull/131/commits/2a8bff1ef705d06fa7bfa9b80a482a87848cfb8d).

**Comment by S-B99** [comment]
Your sprint fix shouldn't include the 32k commits for cleanliness

**Comment by blockparole** [comment]
Ye i just gonna pr again when stuff on `blockparole:master` is resolved or 086 does the patch.

**Comment by S-B99** [comment]
You can just delete this branch, make one for 086 master and add the sprint fix for you want

**Comment by cookiedragon234** [comment]
this is a mess lol, I can create the pr

**Comment by cookiedragon234** [comment]
https://github.com/S-B99/KAMI/pull/46

**Pull request closed without merging**
