### PR TITLE
Try to prevent .set from crashing things by making it parse as JSON + minor refactor

### PR DESCRIPTION
**Pull request by 20kdc**
.set in base master right now always sets a String, which leads to the value being the wrong type, leading to crashes.
The first commit resolves this, adding ISettingUnknown as a 'unknown setting type' base for those settings where one can input/output a string representation, but we don't know what that representation *means*. (This is because Java Generics, when not specified, default to allowing *any* value, which is of course liable to utterly ruin state.)
The second commit cleans up the use of 'Named', and several intermediate classes that appear to have no functional distinction (but do clutter things with instanceof checks)

### CODE REVIEW

**Comment by zeroeightysix** [comment]
This looks great, and honestly the settings system did kind of need a clean up like this.
`ISettingUnknown` is named weirdly though.
May I propose to further merge the functionality of `Setting` into `AbstractSetting` (both are abstract), and rename `ISettingUnknown` to `Setting` instead?

**Comment by 20kdc** [comment]
Huh, neat! That solution also conveniently cleans up the ungenericized types floating around the place, will do.

**Comment by S-B99** [comment]
I believe this also fixes the issue for invalid commands (eg `.asflkas`) crashing

**Comment by 20kdc** [comment]
So apparently there's a lot of usages of the form:
`private Setting<T> xyz = ...`
Unfortunately, these make sense as-is, so it'd be odd to rename Setting to AbstractSetting here.
Leaving the names alone but still merging AbstractSetting into Setting, for now

**Comment by zeroeightysix** [comment]
Looks good! Sorry for combing back to this so late.

**Pull request merged**
